"""AEGIS Data Models - Unified Schema for Security Events"""

from datetime import datetime
from typing import Any, Dict, List, Optional, Union
from enum import Enum
from pydantic import BaseModel, Field
import uuid


class EventType(str, Enum):
    """Types of security events"""

    LOGIN = "login"
    LOGOUT = "logout"
    FILE_ACCESS = "file_access"
    FILE_DELETE = "file_delete"
    FILE_MODIFY = "file_modify"
    NETWORK_CONNECTION = "network_connection"
    DNS_QUERY = "dns_query"
    PROCESS_CREATE = "process_create"
    PRIVILEGE_ESCALATION = "privilege_escalation"
    DATA_EXFILTRATION = "data_exfiltration"
    AUTHENTICATION_FAILURE = "authentication_failure"
    AUTHENTICATION_SUCCESS = "authentication_success"
    CONFIGURATION_CHANGE = "configuration_change"
    PERMISSION_CHANGE = "permission_change"


class Severity(str, Enum):
    """Alert severity levels"""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class AlertStatus(str, Enum):
    """Alert status for workflow"""

    NEW = "new"
    IN_PROGRESS = "in_progress"
    RESOLVED = "resolved"
    FALSE_POSITIVE = "false_positive"
    CLOSED = "closed"


class EntityType(str, Enum):
    """Types of entities being monitored"""

    USER = "user"
    HOST = "host"
    IP_ADDRESS = "ip_address"
    APPLICATION = "application"
    SERVICE = "service"
    DATABASE = "database"


class AttackType(str, Enum):
    """Known attack patterns"""

    BRUTE_FORCE = "brute_force"
    PASS_THE_HASH = "pass_the_hash"
    LATERAL_MOVEMENT = "lateral_movement"
    DATA_EXFILTRATION = "data_exfiltration"
    INSIDER_THREAT = "insider_threat"
    ZERO_DAY = "zero_day"
    CREDENTIAL_THEFT = "credential_theft"
    PRIVILEGE_ESCALATION = "privilege_escalation"
    UNKNOWN = "unknown"


class RawEvent(BaseModel):
    """Raw event from any source (Windows, Linux, Cloud, etc.)"""

    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    source_type: str  # windows, linux, cloudtrail, firewall, dns
    source_ip: Optional[str] = None
    destination_ip: Optional[str] = None
    hostname: Optional[str] = None
    username: Optional[str] = None
    event_type: str
    raw_data: Dict[str, Any]
    raw_message: str

    class Config:
        json_encoders = {datetime: lambda v: v.isoformat()}


class NormalizedEvent(RawEvent):
    """Normalized event in OCSF schema format"""

    entity_id: str  # Unique identifier for the source entity
    entity_type: EntityType
    session_id: Optional[str] = None
    process_id: Optional[str] = None
    command_line: Optional[str] = None
    file_path: Optional[str] = None
    dns_query: Optional[str] = None
    url: Optional[str] = None
    user_agent: Optional[str] = None
    location: Optional[Dict[str, float]] = None  # lat, lon
    isp: Optional[str] = None
    country: Optional[str] = None
    city: Optional[str] = None


class Entity(BaseModel):
    """Entity being monitored (User, Host, IP, etc.)"""

    entity_id: str
    entity_type: EntityType
    name: str
    department: Optional[str] = None
    team: Optional[str] = None
    risk_score: float = 0.0
    first_seen: datetime = Field(default_factory=datetime.utcnow)
    last_seen: datetime = Field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    is_active: bool = True


class EntityBehavior(BaseModel):
    """Behavioral baseline for an entity"""

    entity_id: str
    entity_type: EntityType
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    features: Dict[str, float]
    confidence: float = 0.0
    baseline_version: int = 1


class FeatureVector(BaseModel):
    """Feature vector for ML model input"""

    entity_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    window_size: int  # in seconds
    features: Dict[str, float]
    is_valid: bool = True


class Alert(BaseModel):
    """Security alert generated by the system"""

    alert_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    entity_id: str
    entity_type: EntityType
    severity: Severity
    attack_type: AttackType = AttackType.UNKNOWN
    confidence: float
    anomaly_score: float  # 0.0 to 1.0 from ML model
    status: AlertStatus = AlertStatus.NEW
    title: str
    description: str
    affected_assets: List[str] = Field(default_factory=list)
    related_alerts: List[str] = Field(default_factory=list)
    feature_importance: Optional[Dict[str, float]] = None
    explanation: Optional[str] = None
    assigned_to: Optional[str] = None
    resolved_at: Optional[datetime] = None
    resolution_notes: Optional[str] = None
    feedback_score: Optional[int] = None  # 1-5 from analyst

    class Config:
        json_encoders = {datetime: lambda v: v.isoformat()}


class AnalystFeedback(BaseModel):
    """Feedback from security analysts"""

    feedback_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    alert_id: str
    analyst_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    is_true_positive: bool
    confidence: int = Field(ge=1, le=5, description="Confidence in the classification")
    notes: Optional[str] = None
    corrected_attack_type: Optional[AttackType] = None
    suggested_action: Optional[str] = None


class GraphNode(BaseModel):
    """Node in the entity relationship graph"""

    node_id: str
    entity_type: EntityType
    properties: Dict[str, Any] = Field(default_factory=dict)


class GraphEdge(BaseModel):
    """Edge in the entity relationship graph"""

    source: str
    target: str
    edge_type: str  # "accessed", "connected_to", "member_of"
    weight: float = 1.0
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    properties: Dict[str, Any] = Field(default_factory=dict)


class GraphRelationship(BaseModel):
    """Complete graph relationship"""

    nodes: List[GraphNode]
    edges: List[GraphEdge]


class ModelPrediction(BaseModel):
    """Prediction from ML model"""

    model_name: str
    anomaly_score: float  # 0.0 to 1.0
    is_anomaly: bool
    confidence: float
    feature_contributions: Dict[str, float] = Field(default_factory=dict)
    explanation: Optional[str] = None


class EnsemblePrediction(BaseModel):
    """Combined prediction from ensemble of models"""

    entity_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    predictions: List[ModelPrediction]
    final_score: float
    final_decision: bool  # True if anomaly detected
    consensus_level: float  # Agreement among models
